"""Synthetic Betfair-odds lookup loaded from CSV on bot startup.

The CSV is generated by scripts/build_synthetic_odds_lookup.py and
maps (league_short, market_line, goals_total, minute_bucket) → median
historical Betfair LTP at that state. Used as the in-play odds gate in
alert-only mode — SofaScore odds turned out to be too stale.

API:
  load_lookup(path=None) -> Lookup  (called once on startup; cached)
  Lookup.median(league_short, line, goals_total, minute) -> (odds, n) | (None, 0)
"""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Iterable

# SofaScore unique-tournament id -> short league code (matches the CSV's keys).
TOURNAMENT_TO_SHORT: dict[int, str] = {
    17:  "PL",
    8:   "ESP",
    23:  "ITA",
    35:  "GER",
    34:  "FRA",
    242: "MLS",
    325: "BRA",
}

# Bucket boundary (each 10 min wide, [lo, hi)).
_BUCKETS: list[tuple[int, int, str]] = [
    (30, 40, "30-40"), (40, 50, "40-50"), (50, 60, "50-60"),
    (60, 70, "60-70"), (70, 80, "70-80"), (80, 90, "80-90"),
]

# Minimum sample size in a specific bucket before we trust it. Below this
# we fall back to the (league, line, goals_total) 'all' aggregate.
_MIN_BUCKET_N = 10


def _bucket_for(minute: int) -> str:
    for lo, hi, label in _BUCKETS:
        if lo <= minute < hi:
            return label
    if minute >= 90:
        return "80-90"  # late stoppage time bucketed with 80-90
    return "30-40"     # very early triggers (shouldn't happen given min_min=30)


class Lookup:
    """Map (league, line, goals_total, bucket) -> (median, n)."""

    def __init__(self, rows: Iterable[dict]) -> None:
        self._data: dict[tuple, tuple[float, int]] = {}
        for r in rows:
            key = (r["league"], float(r["line"]), int(r["goals_total"]),
                   r["minute_bucket"])
            self._data[key] = (float(r["median_odds"]), int(r["n"]))

    def median(self, league_short: str, line: float, goals_total: int,
               minute: int) -> tuple[float | None, int]:
        """Look up the (median Betfair LTP, sample n) for this state.

        Tries the precise minute bucket first; if its n < _MIN_BUCKET_N or
        no data, falls back to the 'all' aggregate for the (league, line,
        goals_total) triple. Returns (None, 0) if nothing is available.
        """
        bucket = _bucket_for(minute)
        precise = self._data.get((league_short, line, goals_total, bucket))
        if precise and precise[1] >= _MIN_BUCKET_N:
            return precise
        fallback = self._data.get((league_short, line, goals_total, "all"))
        if fallback:
            return fallback
        return (None, 0)


_cached: Lookup | None = None


def load_lookup(path: str | Path | None = None) -> Lookup:
    """Read the CSV and return a cached Lookup."""
    global _cached
    if _cached is not None:
        return _cached
    if path is None:
        path = Path(__file__).resolve().parents[1] / "data" / "synthetic_odds_lookup.csv"
    rows: list[dict] = []
    with open(path, newline="", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            rows.append(r)
    _cached = Lookup(rows)
    return _cached


def short_for_tournament(tournament_id: int | None) -> str | None:
    return TOURNAMENT_TO_SHORT.get(int(tournament_id)) if tournament_id is not None else None
